# comments
bullet_char: "*"
enable_markup: false

# formatting
dangle_parens: true
dangle_align: prefix
enum_char: .
line_ending: unix
line_width: 120
max_subgroups_hwrap: 2
max_pargs_hwrap: 3
separate_ctrl_name_with_space: false
separate_fn_name_with_space: false
tab_size: 2
enable_sort: true
autosort: true
keyword_case: upper
output_encoding: utf-8

# Custom functions
additional_commands:
  # example:
  foo:
    flags:
      - BAR
      - BAZ
    kwargs:
      DEPENDS: "*"
      HEADERS: "*"
      SOURCES: "*"
